# python-saithrift package

PYTHON_SAITHRIFT_NEPHOS = python-saithrift_0.9.4_amd64.deb
$(PYTHON_SAITHRIFT_NEPHOS)_SRC_PATH = $(SRC_PATH)/SAI
$(PYTHON_SAITHRIFT_NEPHOS)_DEPENDS += $(NEPHOS_SAI_DEV) $(THRIFT_COMPILER) $(PYTHON_THRIFT) $(LIBTHRIFT_DEV)
<<<<<<< HEAD
SONIC_DPKG_DEBS += $(PYTHON_SAITHRIFT_NEPHOS)
=======
#SONIC_DPKG_DEBS += $(PYTHON_SAITHRIFT_NEPHOS)
>>>>>>> 6453b3ac1b961bbff5b608bc29f23708cabfcf70
